### ISSUE TITLE
 Click Fingerprint compatibility and Get Image function

### ISSUE THREAD

**Issue by eron93br** [MikroElektronika/Click_Fingerprint_GTS-511E2#2]
Hello , 

First of all thanks for the contribution to the github community

 I would like to know in which format the image is processed (RAW, BMP, PNG... etc) from the fingerprint_capture_image() function.

 I'm planning to use this module with the Raspberry Pi to post-process the image on the Pi board. Do you suggest this module and think that there is a compatibility with it?

cheers

**Comment by ViktorMilovanovic** [comment]
Hello there,

The processed picture is a 8bit BMP. The firmware for the click was designed to work as a SPI slave, which works fine when the master is an STM or NXP ARM MCU. However, we have not tried to set up a SPI communication between a Raspberry Pi master and the fingerprint slave. Therefore, I cannot really give you any confirmation whether this would be possible. 
On the other hand, if the SPI communication happens to be successful, I don't see any other reason to not use this board along with your Raspberry Pi.

I hope this has helped your situation a little bit.

Best regards.

Viktor Milovanovic

**Comment by eron93br** [comment]
Thanks Viktor, 

Best
